server:
  port: 8081
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/user_account'
    username: 'postgres'
    password: 'mate92'
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
    enabled: true
  kafka:
    bootstrap-servers: 'localhost:9092'
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${app.name}
      auto-offset-reset: earliest


app:
  name: 'accountservice'
  kafka:
    producer:
      topic: 'registration'
    consumer:
      topic: 'successful_registration'




